# Generated by Django 5.0.6 on 2024-06-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiinscripciones', '0001_initial'),
        ('apitutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='tutor_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitutores.tutoralumno'),
        ),
        migrations.AddField(
            model_name='arancel',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles', to='apiinscripciones.inscripcion'),
        ),
    ]
