# Generated by Django 5.0.6 on 2024-06-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tut_descuento',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tut_hijos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='alum_ci',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alum_id',
            field=models.CharField(default=0, max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_id',
            field=models.CharField(default=0, max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_ruc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_ci',
            field=models.CharField(max_length=8),
        ),
    ]
