# Generated by Django 5.0.6 on 2024-06-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0002_remove_alumno_id_remove_tutor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alum_ci',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
