# Generated by Django 5.0.6 on 2024-06-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0003_alter_alumno_alum_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alum_id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
