# Generated by Django 5.0.6 on 2024-06-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0004_alter_alumno_alum_id_alter_tutor_tut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alum_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
