# Generated by Django 5.0.6 on 2024-06-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0005_alter_alumno_alum_id_alter_tutor_tut_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='contrato_fecha',
            new_name='ins_contrato_fecha',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='fecha_inscripcion',
            new_name='ins_fecha',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ins_descuento',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_hijos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
