# Generated by Django 5.0.6 on 2024-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0006_rename_contrato_fecha_inscripcion_ins_contrato_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='ins_cuota',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ins_estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Inscripto', 'Inscripto')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ins_hab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ins_periodo',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
