# Generated by Django 5.0.6 on 2024-06-03 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0007_inscripcion_ins_cuota_inscripcion_ins_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arancel_nivel', models.CharField(choices=[('Escolar Básica', 'Escolar Básica'), ('Nivel Inicial', 'Nivel Inicial'), ('Educación Media', 'Educación Media')], max_length=20)),
                ('arancel_ciclo', models.CharField(blank=True, choices=[('Preescolar', 'Preescolar'), ('1º', '1º'), ('2º', '2º'), ('3º', '3º'), ('Bachillerato', 'Bachillerato')], max_length=20, null=True)),
                ('arancel_especializacion', models.CharField(blank=True, choices=[('BTI', 'BTI'), ('BTA', 'BTA'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Ciencias Básicas', 'Ciencias Básicas')], max_length=20, null=True)),
                ('arancel_grado', models.CharField(blank=True, choices=[('Pre Jardín', 'Pre Jardín'), ('Jardín', 'Jardín'), ('Preescolar', 'Preescolar'), ('1º', '1º'), ('2º', '2º'), ('3º', '3º'), ('4º', '4º'), ('5º', '5º'), ('6º', '6º'), ('7º', '7º'), ('8º', '8º'), ('9º', '9º'), ('1º Bachillerato', '1º Bachillerato'), ('2º Bachillerato', '2º Bachillerato'), ('3º Bachillerato', '3º Bachillerato')], max_length=20, null=True)),
                ('arancel_turno', models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=20, null=True)),
                ('arancel_matricula', models.PositiveIntegerField(default=500000)),
                ('arancel_cuota', models.PositiveIntegerField()),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aranceles', to='apialumnos.inscripcion')),
            ],
        ),
    ]
