# Generated by Django 5.0.6 on 2024-06-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apialumnos', '0008_arancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='tutor_alumno',
        ),
        migrations.RemoveField(
            model_name='tutoralumno',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutoralumno',
            name='alumno',
        ),
        migrations.DeleteModel(
            name='Arancel',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorAlumno',
        ),
    ]
